/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GerenciamentoRouteImport } from './routes/gerenciamento'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as IndexRouteImport } from './routes/index'

const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciamentoRoute = GerenciamentoRouteImport.update({
  id: '/gerenciamento',
  path: '/gerenciamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/cotacoes': typeof CotacoesRoute
  '/gerenciamento': typeof GerenciamentoRoute
  '/import': typeof ImportRoute
  '/inventario': typeof InventarioRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/cotacoes': typeof CotacoesRoute
  '/gerenciamento': typeof GerenciamentoRoute
  '/import': typeof ImportRoute
  '/inventario': typeof InventarioRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/cotacoes': typeof CotacoesRoute
  '/gerenciamento': typeof GerenciamentoRoute
  '/import': typeof ImportRoute
  '/inventario': typeof InventarioRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/cotacoes'
    | '/gerenciamento'
    | '/import'
    | '/inventario'
    | '/lancamentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastros'
    | '/cotacoes'
    | '/gerenciamento'
    | '/import'
    | '/inventario'
    | '/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/cotacoes'
    | '/gerenciamento'
    | '/import'
    | '/inventario'
    | '/lancamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRoute
  CotacoesRoute: typeof CotacoesRoute
  GerenciamentoRoute: typeof GerenciamentoRoute
  ImportRoute: typeof ImportRoute
  InventarioRoute: typeof InventarioRoute
  LancamentosRoute: typeof LancamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciamento': {
      id: '/gerenciamento'
      path: '/gerenciamento'
      fullPath: '/gerenciamento'
      preLoaderRoute: typeof GerenciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRoute,
  CotacoesRoute: CotacoesRoute,
  GerenciamentoRoute: GerenciamentoRoute,
  ImportRoute: ImportRoute,
  InventarioRoute: InventarioRoute,
  LancamentosRoute: LancamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
